### ISSUE TITLE
LoRA tuning for few-shot adaptation

### ISSUE THREAD

**Issue by zappy586** [Asad-Ismail/Grounding-Dino-FineTuning#6]
Hey @Asad-Ismail,
Is there a way to fine-tune GDINO with LoRA adapters using your code? If its possible, can you please add a sample code to show how its done?
Thanks!

**Comment by tz3458172** [comment]
Same question，and is there a way to fine-tune gdino with p-tuning？

**Comment by Asad-Ismail** [comment]
Will be prioritizing this feature this week apologies for delay so far.

**Comment by Asad-Ismail** [comment]
Added Lora finetuning using PEFT from HF, please see this PR https://github.com/Asad-Ismail/Grounding-Dino-FineTuning/pull/15
