### ISSUE TITLE
Add complete example dataset with images and annotations

### ISSUE THREAD

**Issue by Asad-Ismail** [Asad-Ismail/Grounding-Dino-FineTuning#8]
Add complete small scale dataset 100-200 images + annotations to show performance before and after finetuning

**Comment by cristinayyds** [comment]
Hi, I would like to ask how much training data was used during fine-tuning and how many epochs were trained to achieve this result?

**Comment by Asad-Ismail** [comment]
Hello I would say it depends on how hard the problem is for fruit parts seperation like shown in the repo finetuning only took 100 images to train the model we did train it for 10000 iterations best val results were already acheived around 50k iterations  (50 epochs)

**Comment by cristinayyds** [comment]
Thank you for your reply.
